trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:  
- script: |
- task: AzureCLI@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm run-command invoke --name ".\run.cmd" --vm-name "demoVM2" --resource-group "demoVM2_group" --script "C:\agent\run.cmd"'
