trigger:
  - main

pool:
  vmImage: 'windows-latest'


steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Start the self-hosted agent
      New-Item -Path 'D:\Agent\Sample.txt' -ItemType Directory
