trigger:
  - main

pool:
  vmImage: 'windows-latest'
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'D:\agent\vengat.ps1'
    # arguments: '-param1 value1 -param2 value2'
    # workingDirectory: 'D:\agent\vengat.ps1'

