trigger:
  - main

pool:
  vmImage: 'windows-latest'
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'powershell.exe -ExecutionPolicy Bypass -File "D:\Agent\vengat.ps1"'

