trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:  
- script: |
- task: AzureCLI@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm run-command invoke --command-id RunPowerShellScript --name demoVM2 --resource-group demoVM2_group --scripts "C:\agent\run.cmd"'