trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:  
- script: |
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $resourceGroup = "demoVM2_group"
      $vmName = "demoVM2"
      $commandId = "RunCommandScript"
      $scriptPath = "cd C:\Users\vengatesan\agent"
      $scriptPath = "run.cmd"
      
      $scriptContent = Get-Content $scriptPath -Raw
      $encodedScript = [System.Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($scriptContent))
      
      $commandParams = @{
          "commandId" = $commandId
          "script" = $encodedScript
      }
      
      Set-AzVMCustomScriptExtension -ResourceGroupName $resourceGroup -VMName $vmName -Location "eastus" -Name "RunCustomScript" -TypeHandlerVersion "1.10" -FileUri "https://raw.githubusercontent.com/Azure/azure-linux-extensions/master/CustomScriptExtension-1.10.4/CustomScriptLinux" -CommandParameter $commandParams
      
      Update-AzVM -ResourceGroupName $resourceGroup -VMName $vmName