trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Set the URL for your Azure DevOps organization and the name of the agent pool you want to use
      $organizationUrl = "https://dev.azure.com/KVMF"
      $poolName = "Default"
      
      # Set the name and working directory for the agent
      $agentName = "demoVM2"
      $agentWorkingDirectory = "C:\agents\$agentName"
      
      # Download and extract the agent package to the working directory
      Invoke-WebRequest -Uri "$organizationUrl/_apis/distributedtask/agentpackage" -OutFile agent.zip
      Expand-Archive agent.zip -DestinationPath $agentWorkingDirectory
      
      # Configure the agent with the appropriate settings
      cd $agentWorkingDirectory
      ./config.cmd --url $organizationUrl --pool $poolName --agent $agentName --work $agentWorkingDirectory --runAsService
      
      # Start the agent service
      Start-Service vstsagent.$agentName
