trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'vengat-sc-devops'
    ScriptType: 'InlineScript'
    Inline: |
      $organizationUrl = "https://dev.azure.com/KVMF"
            $poolName = "Default"
            
            $agentName = "demoVM3"
            $agentWorkingDirectory = "C:\agents\$agentName"
            
            Invoke-WebRequest -Uri "$organizationUrl/_apis/distributedtask/agentpackage" -OutFile agent.zip
            Expand-Archive agent.zip -DestinationPath $agentWorkingDirectory
            
            cd $agentWorkingDirectory
            ./config.cmd --url $organizationUrl --pool $poolName --agent $agentName --work $agentWorkingDirectory --runAsService
            
            Start-Service vstsagent.$agentName
    azurePowerShellVersion: 'LatestVersion'
    
