trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:  
- script: |

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: 'Invoke-AzVMRunCommand -ResourceGroupName ''vengat-sc-devops'' -Name ''demoVM2'' -CommandId ''RunPowerShellScript'' -ScriptPath ''C:\agent\run.cmd'''

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'az vm start --name demoVM2 --resource-group vengat-sc-devops'