trigger:
  - main

pool:
  vmImage: 'windows-latest'
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $vmName = "demoVM2"
      $commandId = "RunCommandScript"
      $scriptPath = "cd D:\agent\vengat.ps1"
      
      $commandParams = @{
          "commandId" = $commandId
          "script" = $scriptPath
      }
      
      Set-AzVMCustomScriptExtension -ResourceGroupName $resourceGroup -VMName $vmName -Location "eastus" -Name "RunCustomScript" -TypeHandlerVersion "1.10" -FileUri "https://raw.githubusercontent.com/Azure/azure-linux-extensions/master/CustomScriptExtension-1.10.4/CustomScriptLinux" -CommandParameter $commandParams
      
      Update-AzVM -ResourceGroupName $resourceGroup -VMName $vmName
