trigger:
  - main

pool:
  vmImage: 'windows-latest'


steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      New-Item -Path 'C:\Sample' -ItemType Directory
          azureSubscription: '0f5caf29-b4f6-44c1-8411-73a47f4c19c6'
          azurePowerShellVersion: 'LatestVersion'
          machineType: 'Windows'
          targetMachines: '20.81.154.101'
