trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:  
- script: |

- task: AzureCLI@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --use-device-code'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account set --subscription 0f5caf29-b4f6-44c1-8411-73a47f4c19c6'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm start --name demoVM2 --resource-group demoVM2_group'

# - task: InstallPipelineAgent@2
#   inputs:
#     azureSubscription: '0f5caf29-b4f6-44c1-8411-73a47f4c19c6'
#     agentPoolName: 'Default'
#     agentName: 'demoVM2'
#     vmImage: 'ubuntu-latest'
#     adminUserName: 'vengatesan' # Replace with your admin username
#     adminPassword: 'Vengatesan17@' # Replace with a reference to a secret variable for your admin password

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'vengat-sc-devops'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az vm run-command invoke -g demoVM2_group -n demoVM2 --command-id RunShellScript --script-path C:\agent\run.cmd'
   
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'vengat-sc-devops'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az vm extension set --resource-group demoVM2_group --vm-name demoVM2 --name CustomScriptExtension --publisher Microsoft.Compute --version 1.9 --settings '{"fileUris":["C:\agent\run.cmd"],"commandToExecute":".\run.cmd"}''
  

- task: AzureCLI@2
  inputs:
    azureSubscription: 'vengat-sc-devops'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    # inlineScript: 'az vm extension set --resource-group demoVM2_group --vm-name demoVM2 --name CustomScriptExtension --publisher Microsoft.Compute --version 1.9 --settings "{"fileUris":["C:\agent\run.cmd"],"commandToExecute":".\run.cmd"}"'
    # inlineScript: 'az vm extension set --resource-group demoVM2_group --vm-name demoVM2 --name CustomScriptExtension --publisher Microsoft.Compute --version 1.9 --settings "{"fileUris":["C:\\agent\\run.cmd"],"commandToExecute":".\\run.cmd"}"'
    # inlineScript:  az vm extension set --resource-group demoVM2_group --vm-name demoVM2 --name CustomScriptExtension --publisher Microsoft.Compute --version 1.9 --settings '{"fileUris":["C:\\agent\\run.cmd"],"commandToExecute":".\\run.cmd"}'
    # inlineScript: az vm extension set --resource-group demoVM2_group --vm-name demoVM2 --name CustomScriptExtension --publisher Microsoft.Compute --version 1.9 --settings '{"fileUris":["C:\\\\agent\\\\run.cmd"],"commandToExecute":".\\\\run.cmd"}'
    inlineScript: az vm extension set --resource-group demoVM2_group --vm-name demoVM2 --name CustomScriptExtension --publisher Microsoft.Compute --version 1.9 --settings "{\"fileUris\":[\"C:\\\\agent\\\\run.cmd\"],\"commandToExecute\":\".\\\\run.cmd\"}"
    agentPoolName: 'Default'
    agentName: 'demoVM2'
    vmImage: 'ubuntu-latest'
    adminUserName: 'vengatesan' # Replace with your admin username
    adminPassword: 'Vengatesan17@' # Replace with a reference to a secret variable for your admin password