trigger:
  - main

pool:
  name: Default
  
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # PowerShell script to create a sample text file on Azure VM
      New-Item -Path 'D:\Agent\vengatesan' -ItemType Directory
