trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:  
- script: |

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '& $env:AGENT_HOMEDIRECTORY\config.cmd --unattended --url https://dev.azure.com/KVMF --auth pat --token vh7ruudhdkdj474kd5p257lidlukvj5de37cuutf25djeeimh7jq --pool Default --agent demo-VM2 --replace --runAsService'

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'vengat-sc-devops'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'Set-AzVMRunCommand -ResourceGroupName "vengat-sc-devops" -VMName "demoVM2" -Location "EastUS" -RunCommandName "RunCommandName" -FilePath "C:\agent\run.cmd"'

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'vengat-sc-devops'
#     scriptType: 'ps'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'D:\Sample'
# #     script: 'New-Item -Path ''D:\Sample'' -ItemType Directory'